# Generated by Django 5.2.6 on 2025-09-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_post_postcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontent',
            old_name='contet_type',
            new_name='content_type',
        ),
    ]
