# Generated by Django 5.2.6 on 2025-09-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_rename_contet_type_postcontent_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontent',
            old_name='content',
            new_name='post',
        ),
    ]
